name: Ansible Playbook
on: push

jobs:
  role-test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: create pythton venv
        run: python3.8 -m venv venv

      - name: molecule test
        run: |
          source ./venv/bin/activate
          pip install --upgrade pip
          pip install sphinx
          make html
          cp -pr _build /tmp/ansible-playbook-coding-guideline
