name: Ansible Coding Guideline
on: push

jobs:
  build_and_deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: create pythton venv
        run: python3.8 -m venv venv

      - name: build contents
        run: |
          source ./venv/bin/activate
          pip install --upgrade pip
          pip install sphinx
          make html

      - name: deploy contents
        run: |
          sudo rm -r /var/www/html/html && sudo cp -pr _build/html /var/www/html/
